// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/billz-2/ofd_connector (interfaces: FiscalDriveLister)
//
// Generated by this command:
//
//	mockgen -destination=/Users/chris/go/github.com/billz/ofd_connector/mock/fiscalDriveList.go -package=mock_ofdconnector github.com/billz-2/ofd_connector FiscalDriveLister
//

// Package mock_ofdconnector is a generated GoMock package.
package mock_ofdconnector

import (
	context "context"
	reflect "reflect"

	ofdconnector "github.com/billz-2/ofd_connector"
	gomock "go.uber.org/mock/gomock"
)

// MockFiscalDriveLister is a mock of FiscalDriveLister interface.
type MockFiscalDriveLister struct {
	ctrl     *gomock.Controller
	recorder *MockFiscalDriveListerMockRecorder
	isgomock struct{}
}

// MockFiscalDriveListerMockRecorder is the mock recorder for MockFiscalDriveLister.
type MockFiscalDriveListerMockRecorder struct {
	mock *MockFiscalDriveLister
}

// NewMockFiscalDriveLister creates a new mock instance.
func NewMockFiscalDriveLister(ctrl *gomock.Controller) *MockFiscalDriveLister {
	mock := &MockFiscalDriveLister{ctrl: ctrl}
	mock.recorder = &MockFiscalDriveListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFiscalDriveLister) EXPECT() *MockFiscalDriveListerMockRecorder {
	return m.recorder
}

// ListFiscalDrives mocks base method.
func (m *MockFiscalDriveLister) ListFiscalDrives(arg0 context.Context) ([]ofdconnector.FiscalDriveReaderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFiscalDrives", arg0)
	ret0, _ := ret[0].([]ofdconnector.FiscalDriveReaderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFiscalDrives indicates an expected call of ListFiscalDrives.
func (mr *MockFiscalDriveListerMockRecorder) ListFiscalDrives(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFiscalDrives", reflect.TypeOf((*MockFiscalDriveLister)(nil).ListFiscalDrives), arg0)
}
