// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/billz-2/ofd_connector (interfaces: FiscalDriveI)
//
// Generated by this command:
//
//	mockgen -destination=/Users/chris/go/github.com/billz/ofd_connector/mock/fiscal_drive.go -package=mock_ofdconnector github.com/billz-2/ofd_connector FiscalDriveI
//

// Package mock_ofdconnector is a generated GoMock package.
package mock_ofdconnector

import (
	context "context"
	reflect "reflect"

	ofdconnector "github.com/billz-2/ofd_connector"
	gomock "go.uber.org/mock/gomock"
)

// MockFiscalDriveI is a mock of FiscalDriveI interface.
type MockFiscalDriveI struct {
	ctrl     *gomock.Controller
	recorder *MockFiscalDriveIMockRecorder
	isgomock struct{}
}

// MockFiscalDriveIMockRecorder is the mock recorder for MockFiscalDriveI.
type MockFiscalDriveIMockRecorder struct {
	mock *MockFiscalDriveI
}

// NewMockFiscalDriveI creates a new mock instance.
func NewMockFiscalDriveI(ctrl *gomock.Controller) *MockFiscalDriveI {
	mock := &MockFiscalDriveI{ctrl: ctrl}
	mock.recorder = &MockFiscalDriveIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFiscalDriveI) EXPECT() *MockFiscalDriveIMockRecorder {
	return m.recorder
}

// FiscalDriveInfo mocks base method.
func (m *MockFiscalDriveI) FiscalDriveInfo(ctx context.Context) (ofdconnector.FiscalDriveInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FiscalDriveInfo", ctx)
	ret0, _ := ret[0].(ofdconnector.FiscalDriveInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FiscalDriveInfo indicates an expected call of FiscalDriveInfo.
func (mr *MockFiscalDriveIMockRecorder) FiscalDriveInfo(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FiscalDriveInfo", reflect.TypeOf((*MockFiscalDriveI)(nil).FiscalDriveInfo), ctx)
}
