// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/billz-2/ofd_connector (interfaces: OfdConnector)
//
// Generated by this command:
//
//	mockgen -destination=/Users/chris/go/github.com/billz/ofd_connector/mock/ofd_connector.go -package=mock_ofdconnector github.com/billz-2/ofd_connector OfdConnector
//

// Package mock_ofdconnector is a generated GoMock package.
package mock_ofdconnector

import (
	reflect "reflect"

	ofdconnector "github.com/billz-2/ofd_connector"
	gomock "go.uber.org/mock/gomock"
)

// MockOfdConnector is a mock of OfdConnector interface.
type MockOfdConnector struct {
	ctrl     *gomock.Controller
	recorder *MockOfdConnectorMockRecorder
	isgomock struct{}
}

// MockOfdConnectorMockRecorder is the mock recorder for MockOfdConnector.
type MockOfdConnectorMockRecorder struct {
	mock *MockOfdConnector
}

// NewMockOfdConnector creates a new mock instance.
func NewMockOfdConnector(ctrl *gomock.Controller) *MockOfdConnector {
	mock := &MockOfdConnector{ctrl: ctrl}
	mock.recorder = &MockOfdConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOfdConnector) EXPECT() *MockOfdConnectorMockRecorder {
	return m.recorder
}

// FiscalDrive mocks base method.
func (m *MockOfdConnector) FiscalDrive() ofdconnector.FiscalDriveI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FiscalDrive")
	ret0, _ := ret[0].(ofdconnector.FiscalDriveI)
	return ret0
}

// FiscalDrive indicates an expected call of FiscalDrive.
func (mr *MockOfdConnectorMockRecorder) FiscalDrive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FiscalDrive", reflect.TypeOf((*MockOfdConnector)(nil).FiscalDrive))
}

// Receipt mocks base method.
func (m *MockOfdConnector) Receipt() ofdconnector.ReceiptI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Receipt")
	ret0, _ := ret[0].(ofdconnector.ReceiptI)
	return ret0
}

// Receipt indicates an expected call of Receipt.
func (mr *MockOfdConnectorMockRecorder) Receipt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Receipt", reflect.TypeOf((*MockOfdConnector)(nil).Receipt))
}

// ZReport mocks base method.
func (m *MockOfdConnector) ZReport() ofdconnector.ZReportI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ZReport")
	ret0, _ := ret[0].(ofdconnector.ZReportI)
	return ret0
}

// ZReport indicates an expected call of ZReport.
func (mr *MockOfdConnectorMockRecorder) ZReport() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ZReport", reflect.TypeOf((*MockOfdConnector)(nil).ZReport))
}
