// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/billz-2/ofd_connector (interfaces: ReceiptI)
//
// Generated by this command:
//
//	mockgen -destination=/Users/chris/go/github.com/billz/ofd_connector/mock/receipt.go -package=mock_ofdconnector github.com/billz-2/ofd_connector ReceiptI
//

// Package mock_ofdconnector is a generated GoMock package.
package mock_ofdconnector

import (
	context "context"
	reflect "reflect"

	ofdconnector "github.com/billz-2/ofd_connector"
	gomock "go.uber.org/mock/gomock"
)

// MockReceiptI is a mock of ReceiptI interface.
type MockReceiptI struct {
	ctrl     *gomock.Controller
	recorder *MockReceiptIMockRecorder
	isgomock struct{}
}

// MockReceiptIMockRecorder is the mock recorder for MockReceiptI.
type MockReceiptIMockRecorder struct {
	mock *MockReceiptI
}

// NewMockReceiptI creates a new mock instance.
func NewMockReceiptI(ctrl *gomock.Controller) *MockReceiptI {
	mock := &MockReceiptI{ctrl: ctrl}
	mock.recorder = &MockReceiptIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReceiptI) EXPECT() *MockReceiptIMockRecorder {
	return m.recorder
}

// GetDatabaseFilesCount mocks base method.
func (m *MockReceiptI) GetDatabaseFilesCount(ctx context.Context, status uint16) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseFilesCount", ctx, status)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabaseFilesCount indicates an expected call of GetDatabaseFilesCount.
func (mr *MockReceiptIMockRecorder) GetDatabaseFilesCount(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseFilesCount", reflect.TypeOf((*MockReceiptI)(nil).GetDatabaseFilesCount), ctx, status)
}

// GetReceiptInfo mocks base method.
func (m *MockReceiptI) GetReceiptInfo(ctx context.Context, index uint32) (ofdconnector.ReceiptFullInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceiptInfo", ctx, index)
	ret0, _ := ret[0].(ofdconnector.ReceiptFullInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceiptInfo indicates an expected call of GetReceiptInfo.
func (mr *MockReceiptIMockRecorder) GetReceiptInfo(ctx, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceiptInfo", reflect.TypeOf((*MockReceiptI)(nil).GetReceiptInfo), ctx, index)
}

// GetTXID mocks base method.
func (m *MockReceiptI) GetTXID(ctx context.Context, req ofdconnector.SaleParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTXID", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTXID indicates an expected call of GetTXID.
func (mr *MockReceiptIMockRecorder) GetTXID(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTXID", reflect.TypeOf((*MockReceiptI)(nil).GetTXID), ctx, req)
}

// RegisterTXID mocks base method.
func (m *MockReceiptI) RegisterTXID(ctx context.Context, txID int64) (ofdconnector.ReceiptInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterTXID", ctx, txID)
	ret0, _ := ret[0].(ofdconnector.ReceiptInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterTXID indicates an expected call of RegisterTXID.
func (mr *MockReceiptIMockRecorder) RegisterTXID(ctx, txID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterTXID", reflect.TypeOf((*MockReceiptI)(nil).RegisterTXID), ctx, txID)
}

// ResetDatabaseFilesStatus mocks base method.
func (m *MockReceiptI) ResetDatabaseFilesStatus(ctx context.Context, txID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetDatabaseFilesStatus", ctx, txID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetDatabaseFilesStatus indicates an expected call of ResetDatabaseFilesStatus.
func (mr *MockReceiptIMockRecorder) ResetDatabaseFilesStatus(ctx, txID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetDatabaseFilesStatus", reflect.TypeOf((*MockReceiptI)(nil).ResetDatabaseFilesStatus), ctx, txID)
}
