// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/billz-2/ofd_connector (interfaces: ZReportI)
//
// Generated by this command:
//
//	mockgen -destination=/Users/chris/go/github.com/billz/ofd_connector/mock/zreport.go -package=mock_ofdconnector github.com/billz-2/ofd_connector ZReportI
//

// Package mock_ofdconnector is a generated GoMock package.
package mock_ofdconnector

import (
	context "context"
	reflect "reflect"

	ofdconnector "github.com/billz-2/ofd_connector"
	gomock "go.uber.org/mock/gomock"
)

// MockZReportI is a mock of ZReportI interface.
type MockZReportI struct {
	ctrl     *gomock.Controller
	recorder *MockZReportIMockRecorder
	isgomock struct{}
}

// MockZReportIMockRecorder is the mock recorder for MockZReportI.
type MockZReportIMockRecorder struct {
	mock *MockZReportI
}

// NewMockZReportI creates a new mock instance.
func NewMockZReportI(ctrl *gomock.Controller) *MockZReportI {
	mock := &MockZReportI{ctrl: ctrl}
	mock.recorder = &MockZReportIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockZReportI) EXPECT() *MockZReportIMockRecorder {
	return m.recorder
}

// CloseZreport mocks base method.
func (m *MockZReportI) CloseZreport(ctx context.Context, closedTime string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseZreport", ctx, closedTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseZreport indicates an expected call of CloseZreport.
func (mr *MockZReportIMockRecorder) CloseZreport(ctx, closedTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseZreport", reflect.TypeOf((*MockZReportI)(nil).CloseZreport), ctx, closedTime)
}

// GetZReportInfo mocks base method.
func (m *MockZReportI) GetZReportInfo(ctx context.Context, index uint32) (ofdconnector.ZReportInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZReportInfo", ctx, index)
	ret0, _ := ret[0].(ofdconnector.ZReportInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZReportInfo indicates an expected call of GetZReportInfo.
func (mr *MockZReportIMockRecorder) GetZReportInfo(ctx, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZReportInfo", reflect.TypeOf((*MockZReportI)(nil).GetZReportInfo), ctx, index)
}

// OpenZreport mocks base method.
func (m *MockZReportI) OpenZreport(ctx context.Context, createdTime string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenZreport", ctx, createdTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// OpenZreport indicates an expected call of OpenZreport.
func (mr *MockZReportIMockRecorder) OpenZreport(ctx, createdTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenZreport", reflect.TypeOf((*MockZReportI)(nil).OpenZreport), ctx, createdTime)
}
