// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.udevs.io/billz/billz_order_service/pkg/httpclient (interfaces: HTTPClient)
//
// Generated by this command:
//
//	mockgen -destination httpclient.go -package mock_httpclient gitlab.udevs.io/billz/billz_order_service/pkg/httpclient HTTPClient
//

// Package mock_httpclient is a generated GoMock package.
package mock_httpclient

import (
	context "context"
	reflect "reflect"

	httpclient "gitlab.udevs.io/billz/ofd_connector/pkg/httpclient"
	gomock "go.uber.org/mock/gomock"
)

// MockHTTPClient is a mock of HTTPClient interface.
type MockHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientMockRecorder
	isgomock struct{}
}

// MockHTTPClientMockRecorder is the mock recorder for MockHTTPClient.
type MockHTTPClientMockRecorder struct {
	mock *MockHTTPClient
}

// NewMockHTTPClient creates a new mock instance.
func NewMockHTTPClient(ctrl *gomock.Controller) *MockHTTPClient {
	mock := &MockHTTPClient{ctrl: ctrl}
	mock.recorder = &MockHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClient) EXPECT() *MockHTTPClientMockRecorder {
	return m.recorder
}

// Request mocks base method.
func (m *MockHTTPClient) Request(ctx context.Context, req *httpclient.HTTPRequest) *httpclient.HTTPResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", ctx, req)
	ret0, _ := ret[0].(*httpclient.HTTPResponse)
	return ret0
}

// Request indicates an expected call of Request.
func (mr *MockHTTPClientMockRecorder) Request(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockHTTPClient)(nil).Request), ctx, req)
}
